In [1]:
import pandas as pd

In [104]:
sample_2014 = pd.read_csv("2014_Crime_Data.csv")
sample_2015 = pd.read_csv("2015_Crime_Data.csv")
sample_2016 = pd.read_csv("2016_Crime_Data.csv")

In [105]:
sample_2014.shape

(10160, 6)

In [106]:
sample_2015.shape

(9643, 6)

In [107]:
sample_2016.shape

(9365, 6)

In [108]:
sample_14_15 = pd.concat([sample_2014, sample_2015])

In [109]:
sample_14_15_16 = pd.concat([sample_14_15, sample_2016])

In [110]:
sample_14_15_16.shape

(29168, 6)

In [111]:
sample_14_15_16.head()

,GO Highest Offense Desc,Highest NIBRS/UCR Offense Description,GO Report Date,GO Location,Clearance Date,GO Location Zip
0,THEFT,Theft: All Other Larceny,02/24/2014 12:00:00 AM,3101 GUADALUPE ST ...,02/25/2014 12:00:00 AM,78705.0
1,THEFT BY SHOPLIFTING,Theft: Shoplifting,08/18/2014 12:00:00 AM,1000 E 41ST ST ...,08/21/2014 12:00:00 AM,78751.0
2,BURGLARY OF VEHICLE,Theft: BOV,08/22/2014 12:00:00 AM,117 W WILLIAM CANNON DR ...,08/27/2014 12:00:00 AM,78745.0
3,AUTO THEFT,Auto Theft,07/19/2014 12:00:00 AM,6407 SPRINGDALE RD ...,07/20/2014 12:00:00 AM,78723.0
4,THEFT,Theft: All Other Larceny,07/14/2014 12:00:00 AM,7201 BLESSING AVE ...,07/15/2014 12:00:00 AM,78752.0

In [112]:
sample_14_15_16 = sample_14_15_16[['GO Highest Offense Desc', 'Highest NIBRS/UCR Offense Description',
       'GO Report Date', 'GO Location', 'GO Location Zip']]

In [113]:
sample_14_15_16.head(3)

,GO Highest Offense Desc,Highest NIBRS/UCR Offense Description,GO Report Date,GO Location,GO Location Zip
0,THEFT,Theft: All Other Larceny,02/24/2014 12:00:00 AM,3101 GUADALUPE ST ...,78705.0
1,THEFT BY SHOPLIFTING,Theft: Shoplifting,08/18/2014 12:00:00 AM,1000 E 41ST ST ...,78751.0
2,BURGLARY OF VEHICLE,Theft: BOV,08/22/2014 12:00:00 AM,117 W WILLIAM CANNON DR ...,78745.0

In [114]:
sample_14_15_16.duplicated().sum()

3605

In [115]:
sample_14_15_16.shape[0] - sample_14_15_16.duplicated().sum()

25563

In [116]:
sample_14_15_16 = sample_14_15_16.drop_duplicates()

In [117]:
sample_14_15_16.shape[0]

25563

In [118]:
sample_14_15_16.isnull().sum()

GO Highest Offense Desc                    0
Highest NIBRS/UCR Offense Description      0
GO Report Date                             0
GO Location                              445
GO Location Zip                          101
dtype: int64

In [119]:
sample_14_15_16 = sample_14_15_16.dropna()

In [120]:
sample_14_15_16.isnull().sum()

GO Highest Offense Desc                  0
Highest NIBRS/UCR Offense Description    0
GO Report Date                           0
GO Location                              0
GO Location Zip                          0
dtype: int64

In [121]:
sample_14_15_16.dtypes

GO Highest Offense Desc                   object
Highest NIBRS/UCR Offense Description     object
GO Report Date                            object
GO Location                               object
GO Location Zip                          float64
dtype: object

In [122]:
sample_14_15_16.head()

,GO Highest Offense Desc,Highest NIBRS/UCR Offense Description,GO Report Date,GO Location,GO Location Zip
0,THEFT,Theft: All Other Larceny,02/24/2014 12:00:00 AM,3101 GUADALUPE ST ...,78705.0
1,THEFT BY SHOPLIFTING,Theft: Shoplifting,08/18/2014 12:00:00 AM,1000 E 41ST ST ...,78751.0
2,BURGLARY OF VEHICLE,Theft: BOV,08/22/2014 12:00:00 AM,117 W WILLIAM CANNON DR ...,78745.0
3,AUTO THEFT,Auto Theft,07/19/2014 12:00:00 AM,6407 SPRINGDALE RD ...,78723.0
4,THEFT,Theft: All Other Larceny,07/14/2014 12:00:00 AM,7201 BLESSING AVE ...,78752.0

In [123]:
sample_14_15_16['Zip'] = sample_14_15_16['GO Location Zip'].astype(int)

In [124]:
sample_14_15_16.head()

,GO Highest Offense Desc,Highest NIBRS/UCR Offense Description,GO Report Date,GO Location,GO Location Zip,Zip
0,THEFT,Theft: All Other Larceny,02/24/2014 12:00:00 AM,3101 GUADALUPE ST ...,78705.0,78705
1,THEFT BY SHOPLIFTING,Theft: Shoplifting,08/18/2014 12:00:00 AM,1000 E 41ST ST ...,78751.0,78751
2,BURGLARY OF VEHICLE,Theft: BOV,08/22/2014 12:00:00 AM,117 W WILLIAM CANNON DR ...,78745.0,78745
3,AUTO THEFT,Auto Theft,07/19/2014 12:00:00 AM,6407 SPRINGDALE RD ...,78723.0,78723
4,THEFT,Theft: All Other Larceny,07/14/2014 12:00:00 AM,7201 BLESSING AVE ...,78752.0,78752

In [125]:
sample_14_15_16['Zip'] = sample_14_15_16['Zip'].astype(str)

In [126]:
sample_14_15_16.head()

,GO Highest Offense Desc,Highest NIBRS/UCR Offense Description,GO Report Date,GO Location,GO Location Zip,Zip
0,THEFT,Theft: All Other Larceny,02/24/2014 12:00:00 AM,3101 GUADALUPE ST ...,78705.0,78705
1,THEFT BY SHOPLIFTING,Theft: Shoplifting,08/18/2014 12:00:00 AM,1000 E 41ST ST ...,78751.0,78751
2,BURGLARY OF VEHICLE,Theft: BOV,08/22/2014 12:00:00 AM,117 W WILLIAM CANNON DR ...,78745.0,78745
3,AUTO THEFT,Auto Theft,07/19/2014 12:00:00 AM,6407 SPRINGDALE RD ...,78723.0,78723
4,THEFT,Theft: All Other Larceny,07/14/2014 12:00:00 AM,7201 BLESSING AVE ...,78752.0,78752

In [127]:
del sample_14_15_16['GO Location Zip']

In [128]:
sample_14_15_16.head()

,GO Highest Offense Desc,Highest NIBRS/UCR Offense Description,GO Report Date,GO Location,Zip
0,THEFT,Theft: All Other Larceny,02/24/2014 12:00:00 AM,3101 GUADALUPE ST ...,78705
1,THEFT BY SHOPLIFTING,Theft: Shoplifting,08/18/2014 12:00:00 AM,1000 E 41ST ST ...,78751
2,BURGLARY OF VEHICLE,Theft: BOV,08/22/2014 12:00:00 AM,117 W WILLIAM CANNON DR ...,78745
3,AUTO THEFT,Auto Theft,07/19/2014 12:00:00 AM,6407 SPRINGDALE RD ...,78723
4,THEFT,Theft: All Other Larceny,07/14/2014 12:00:00 AM,7201 BLESSING AVE ...,78752

In [129]:
sample_14_15_16['City'] = 'Austin'
sample_14_15_16['State'] = 'TX'

In [130]:
sample_14_15_16.head()

,GO Highest Offense Desc,Highest NIBRS/UCR Offense Description,GO Report Date,GO Location,Zip,City,State
0,THEFT,Theft: All Other Larceny,02/24/2014 12:00:00 AM,3101 GUADALUPE ST ...,78705,Austin,TX
1,THEFT BY SHOPLIFTING,Theft: Shoplifting,08/18/2014 12:00:00 AM,1000 E 41ST ST ...,78751,Austin,TX
2,BURGLARY OF VEHICLE,Theft: BOV,08/22/2014 12:00:00 AM,117 W WILLIAM CANNON DR ...,78745,Austin,TX
3,AUTO THEFT,Auto Theft,07/19/2014 12:00:00 AM,6407 SPRINGDALE RD ...,78723,Austin,TX
4,THEFT,Theft: All Other Larceny,07/14/2014 12:00:00 AM,7201 BLESSING AVE ...,78752,Austin,TX

In [131]:
sample_14_15_16['Full_Address'] = sample_14_15_16['GO Location'] + sample_14_15_16['City'] + " " + sample_14_15_16['State'] + " " +  sample_14_15_16['Zip']

In [132]:
sample_14_15_16.head()

,GO Highest Offense Desc,Highest NIBRS/UCR Offense Description,GO Report Date,GO Location,Zip,City,State,Full_Address
0,THEFT,Theft: All Other Larceny,02/24/2014 12:00:00 AM,3101 GUADALUPE ST ...,78705,Austin,TX,3101 GUADALUPE ST ...
1,THEFT BY SHOPLIFTING,Theft: Shoplifting,08/18/2014 12:00:00 AM,1000 E 41ST ST ...,78751,Austin,TX,1000 E 41ST ST ...
2,BURGLARY OF VEHICLE,Theft: BOV,08/22/2014 12:00:00 AM,117 W WILLIAM CANNON DR ...,78745,Austin,TX,117 W WILLIAM CANNON DR ...
3,AUTO THEFT,Auto Theft,07/19/2014 12:00:00 AM,6407 SPRINGDALE RD ...,78723,Austin,TX,6407 SPRINGDALE RD ...
4,THEFT,Theft: All Other Larceny,07/14/2014 12:00:00 AM,7201 BLESSING AVE ...,78752,Austin,TX,7201 BLESSING AVE ...

In [133]:
sample_14_15_16.columns

Index(['GO Highest Offense Desc', 'Highest NIBRS/UCR Offense Description',
       'GO Report Date', 'GO Location', 'Zip', 'City', 'State',
       'Full_Address'],
      dtype='object')

In [134]:
sample_14_15_16 = sample_14_15_16[['Highest NIBRS/UCR Offense Description',
       'GO Report Date',
       'Full_Address']]
sample_14_15_16.head()

,Highest NIBRS/UCR Offense Description,GO Report Date,Full_Address
0,Theft: All Other Larceny,02/24/2014 12:00:00 AM,3101 GUADALUPE ST ...
1,Theft: Shoplifting,08/18/2014 12:00:00 AM,1000 E 41ST ST ...
2,Theft: BOV,08/22/2014 12:00:00 AM,117 W WILLIAM CANNON DR ...
3,Auto Theft,07/19/2014 12:00:00 AM,6407 SPRINGDALE RD ...
4,Theft: All Other Larceny,07/14/2014 12:00:00 AM,7201 BLESSING AVE ...

In [136]:
sample_14_15_16.rename_axis({'Highest NIBRS/UCR Offense Description': 'Offense_Description',
                            'GO Report Date': 'Report_Date'}, axis=1, inplace=True)

In [137]:
sample_14_15_16.head()

,Offense_Description,Report_Date,Full_Address
0,Theft: All Other Larceny,02/24/2014 12:00:00 AM,3101 GUADALUPE ST ...
1,Theft: Shoplifting,08/18/2014 12:00:00 AM,1000 E 41ST ST ...
2,Theft: BOV,08/22/2014 12:00:00 AM,117 W WILLIAM CANNON DR ...
3,Auto Theft,07/19/2014 12:00:00 AM,6407 SPRINGDALE RD ...
4,Theft: All Other Larceny,07/14/2014 12:00:00 AM,7201 BLESSING AVE ...

In [138]:
m = {'Agg Assault': 'Agg Assault',
     'Theft': 'Theft',
     'Robbery': 'Robbery',
     'Burglary': 'Burglary',
     'Auto Theft': 'Theft: Auto Theft',
     'Murder' : 'Murder',
     'Burglary / \nBreaking & Entering': 'Burglary: Breaking & Entering',
     'Homicide: Murder & Nonnegligent Manslaughter': 'Homicide: Murder & Non-negligent Manslaughter',
     'Aggravated Assault': 'Aggravated Assault',
     'Theft: Pocket Picking': 'Theft: Pocket Picking',
     'Theft: Purse Snatching': 'Theft: Purse Snatching',
     'Theft: Shoplifting': 'Theft: Shoplifting',
     'Theft: from Building': 'Theft: from Building',
     'Theft: Coin Op Machine': 'Theft: Coin Op Machine',
     'Theft: BOV': 'Theft: BOV',
     'Theft: Auto Parts': 'Theft: Auto Parts',
     'Theft: All Other Larceny': 'Theft: All Other Larceny'}

In [139]:
sample_14_15_16['Offense_Description'] = sample_14_15_16.Offense_Description.map(m)

In [140]:
sample_14_15_16

,Offense_Description,Report_Date,Full_Address
0,Theft: All Other Larceny,02/24/2014 12:00:00 AM,3101 GUADALUPE ST ...
1,Theft: Shoplifting,08/18/2014 12:00:00 AM,1000 E 41ST ST ...
2,Theft: BOV,08/22/2014 12:00:00 AM,117 W WILLIAM CANNON DR ...
3,Theft: Auto Theft,07/19/2014 12:00:00 AM,6407 SPRINGDALE RD ...
4,Theft: All Other Larceny,07/14/2014 12:00:00 AM,7201 BLESSING AVE ...
5,Aggravated Assault,07/19/2014 12:00:00 AM,E WILLIAM CANNON DR / S IH 35 SVRD NB ...
6,Theft: Shoplifting,02/18/2014 12:00:00 AM,1030 NORWOOD PARK BLVD ...
7,Theft: BOV,01/30/2014 12:00:00 AM,1803 E ANDERSON LN SVRD EB ...
8,Theft: Shoplifting,06/25/2014 12:00:00 AM,7301 N FM 620 RD ...
9,Theft: All Other Larceny,06/13/2014 12:00:00 AM,309 E GRADY DR ...
10,Theft: BOV,10/29/2014 12:00:00 AM,6013 S 1ST ST ...
11,Theft: All Other Larceny,01/07/2014 12:00:00 AM,2525 W ANDERSON LN ...
12,Theft: All Other Larceny,01/13/2014 12:00:00 AM,9300 S IH 35 SVRD SB ...
13,Theft: All Other Larceny,10/03/2014 12:00:00 AM,10900 LAKELINE MALL DR ...
14,Burglary: Breaking & Entering,04/16/2014 12:00:00 AM,10408 O ROURK LN ...
15,Theft: Shoplifting,11/30/2014 12:00:00 AM,1030 NORWOOD PARK BLVD ...
16,Theft: from Building,12/07/2014 12:00:00 AM,8601 RESEARCH BLVD NB ...
17,Theft: All Other Larceny,01/22/2014 12:00:00 AM,1000 E 41ST ST ...
18,Burglary: Breaking & Entering,12/27/2014 12:00:00 AM,9205 RESEARCH BLVD SVRD NB ...
19,Theft: Shoplifting,06/17/2014 12:00:00 AM,11200 LAKELINE MALL DR ...
20,Theft: All Other Larceny,11/11/2014 12:00:00 AM,9323 MANCHACA RD ...
21,Burglary: Breaking & Entering,03/26/2014 12:00:00 AM,6408 ROSEBOROUGH DR ...
22,Theft: All Other Larceny,03/29/2014 12:00:00 AM,1221 ALGARITA AVE ...
23,Theft: All Other Larceny,04/11/2014 12:00:00 AM,401 LITTLE TEXAS LN ...
24,Theft: BOV,03/24/2014 12:00:00 AM,6301 E US 290 HWY EB ...
25,Theft: Shoplifting,09/25/2014 12:00:00 AM,2110 W SLAUGHTER LN ...
26,Theft: BOV,02/08/2014 12:00:00 AM,6607 BRODIE LN ...
27,Aggravated Assault,05/18/2014 12:00:00 AM,9070 RESEARCH BLVD SVRD SB ...
28,Theft: Auto Theft,11/13/2014 12:00:00 AM,11001 S 1ST ST ...
29,Theft: All Other Larceny,11/07/2014 12:00:00 AM,403 E 15TH ST ...
...,...,...,...
9324,Theft,19-Jan-16,3500 JEFFERSON ST ...
9326,Theft: Auto Theft,5-Sep-16,2508 E RIVERSIDE DR ...
9327,Burglary,18-Mar-16,5330 N IH 35 SVRD SB ...
9328,Burglary,19-Nov-16,7415 POINSETTA LN ...
9329,Theft,22-Feb-16,3600 S IH 35 SVRD SB ...
9330,Theft,6-May-16,1201 BARBARA JORDAN BLVD ...
9331,Theft,5-Apr-16,2223 BURTON DR ...
9332,Theft,25-Jul-16,9333 RESEARCH BLVD NB ...
9333,Theft,20-Jul-16,6806 E RIVERSIDE DR ...
9338,Theft,26-Sep-16,1101 S MOPAC EXPY SVRD NB ...
9339,Theft,18-Jun-16,1030 NORWOOD PARK BLVD ...
9340,Theft,11-May-16,500 E 4TH ST ...
9341,Theft,16-Sep-16,2300 W BEN WHITE BLVD SVRD EB ...
9342,Theft,4-Mar-16,12330 METRIC BLVD ...
9343,Theft,11-Dec-16,710 E BEN WHITE BLVD WB ...
9344,Theft,19-Mar-16,6934 E BEN WHITE BLVD EB ...
9345,Theft,17-Oct-16,1003 BARTON SPRINGS RD ...
9346,Theft,18-Mar-16,11066 PECAN PARK BLVD ...
9347,Theft,2-Oct-16,9505 STONELAKE BLVD ...
9348,Agg Assault,29-Jun-16,1637 PAVELICH PASS ...
9351,Theft,4-Jul-16,11600 FAST HORSE DR ...
9353,Burglary,1-Feb-16,6503 BLUFF SPRINGS RD ...
9355,Theft,24-Aug-16,8313 PANADERO DR ...
9356,Theft,16-Feb-16,12800 TURTLE ROCK RD ...
9357,Burglary,8-Feb-16,6208 BLUE STEM TRL ...
9360,Theft,7-Feb-16,4712 S CONGRESS AVE ...
9361,Theft,8-Oct-16,2336 DOUGLAS ST ...
9362,Theft,3-May-16,5601 ADAIR DR ...
9363,Theft,23-Feb-16,3603 SOUTHRIDGE DR ...
9364,Theft,15-Nov-16,2508 E RIVERSIDE DR ...

In [141]:
sample_14_15_16.to_csv("Crime_Samples.csv")